#line 2 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\/pbrtlex.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
static yyconst short int yy_accept[344] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       66,   64,   44,   45,   50,    8,   64,   64,   46,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   48,   49,   44,   62,   63,   61,   62,
        9,   10,    4,    2,   65,    3,    6,    6,    5,   44,
        0,   46,   46,   46,    0,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       44,   60,   59,   56,   60,   57,   54,   55,   51,   53,
       52,    2,    7,   46,    0,   46,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,    0,   47,   47,   47,   47,   47,   47,   19,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   58,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   32,   47,   33,   47,   47,   47,
       47,   47,   47,   47,   47,   15,   47,   47,   47,   47,
       47,   47,   22,   47,   47,   47,   47,   29,   47,   47,
       47,   47,   47,   47,   40,   47,   47,   47,   47,   47,

       47,   47,   47,   47,    1,   47,   47,   47,   47,   47,
       47,   47,   30,   47,   47,   35,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   20,   47,   23,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   43,   47,   47,   47,   47,   47,   47,   47,   47,
       25,   47,   47,   47,   47,   47,   38,   39,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   31,   47,   47,   47,   47,   42,   11,   47,
       47,   47,   47,   47,   47,   21,   24,   47,   27,   47,
       47,   47,   47,   47,   47,   47,   14,   47,   47,   47,

       47,   47,   47,   47,   37,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   13,   47,   47,
       47,   26,   47,   47,   36,   47,   12,   16,   47,   47,
       47,   47,   47,   47,   17,   47,   47,   41,   18,   47,
       34,   28,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    6,    1,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,    1,    1,
        1,    1,    1,    1,   11,   12,   13,   14,   15,   16,
       14,   14,   17,   14,   14,   18,   19,   14,   20,   21,
       14,   22,   23,   24,   14,   25,   26,   14,   14,   14,
       27,   28,   29,    1,   14,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   14,   46,   47,   48,   49,   50,   14,   51,
       52,   14,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    2,    1,    1,    1,    1,    2,    2,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1
    } ;

static yyconst short int yy_base[351] =
    {   0,
        0,    0,   51,   53,  436,  435,   56,   59,  112,  165,
      437,  440,   68,  440,  440,  440,   56,  426,   57,   36,
        0,   39,  397,   42,   33,  404,  402,  394,   44,   62,
       56,  387,  386,  440,  440,   71,  440,  440,  440,  216,
      440,  440,  440,   74,  440,  440,  440,    0,  440,   78,
      419,  118,  120,  122,  136,    0,  396,  393,  378,  383,
       62,  383,  389,  390,  385,  376,  371,  379,  366,  366,
      367,  372,  383,  382,  381,  364,  358,  378,  366,  360,
      121,  440,  440,  440,  395,  440,  440,  440,  440,  440,
      440,  132,    0,  143,  394,  393,  368,  371,  354,  365,

      366,  351,  354,  352,  353,  356,  352,  357,  356,  355,
      354,  357,  341,  344,  338,  338,  347,  333,  337,  330,
      337,  367,  335,  357,  336,  327,  342,  338,    0,  322,
      320,  320,  356,  320,  333,  323,  317,  314,  320,  326,
      327,  324,  327,  307,  308,  312,  320,  440,  318,  313,
      319,  319,  300,  121,  309,  313,  322,  296,  305,  294,
      325,  293,  305,  304,    0,  300,    0,  304,  289,   52,
      300,   85,  287,  296,  282,    0,  306,  277,  285,  279,
      292,  281,    0,  294,  133,  285,  288,    0,  275,  299,
      285,  284,  273,  286,  298,  280,  270,  282,  274,  262,

      263,  261,  277,  254,    0,  256,  263,  269,  259,  258,
      259,  279,    0,  268,  280,    0,  250,  247,  251,  257,
      259,  243,  242,  255,  258,  263,  238,    0,  239,    0,
      248,  250,  235,  215,  215,  212,  215,  215,  222,  207,
      216,    0,  209,  229,  145,  207,  203,  214,  214,  207,
        0,  195,  208,  203,  203,  191,  149,    0,  204,  194,
      190,  191,  200,  190,  185,  201,  207,  195,  185,  197,
      179,  190,    0,  189,  188,  178,  181,    0,    0,  167,
      179,  181,  178,  169,  159,    0,    0,  167,    0,  166,
      172,  171,  173,  159,  158,  165,    0,  158,  154,  153,

      167,  150,  151,  158,    0,  165,  159,  147,  143,  153,
      139,  152,  154,  152,  138,  132,  145,    0,  136,  132,
      141,    0,  125,  119,    0,  119,    0,    0,  109,  107,
      109,   94,   90,   78,    0,   70,   57,    0,    0,   52,
        0,    0,  440,  264,  267,  270,  273,   71,  276,  278
    } ;

static yyconst short int yy_def[351] =
    {   0,
      343,    1,  344,  344,  345,  345,  346,  346,  347,  347,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  343,  343,  348,  343,  343,  343,  349,
      343,  343,  343,  343,  343,  343,  343,  350,  343,  343,
      343,  343,  343,  343,  343,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  350,  343,  343,  343,  348,  348,  348,  348,

      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  343,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  343,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,

      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,

      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,    0,  343,  343,  343,  343,  343,  343,  343
    } ;

static yyconst short int yy_nxt[494] =
    {   0,
       12,   13,   14,   15,   16,   17,   17,   18,   12,   19,
       20,   21,   22,   21,   21,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   12,   35,   36,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       36,   21,   13,   38,   39,   38,   39,   44,   45,   46,
       44,   45,   46,   51,   54,   52,   52,   57,   60,   50,
       65,   55,   50,   56,   63,   92,   66,   70,   40,   50,
       40,   58,   61,   59,   64,   44,  193,   71,   44,   77,
       55,   72,  194,   73,  342,   74,  196,   50,   75,  197,

       81,   78,  341,   92,  101,  102,   44,   50,   44,   44,
       76,   44,   47,  340,   45,   49,   47,   47,   50,  339,
       50,   81,   50,   50,   92,   54,   92,   52,   50,   53,
       50,   94,   55,   92,   55,  338,   55,  337,   47,   47,
       47,   95,   95,  178,  208,   96,  336,  209,  335,  210,
       81,   55,   94,   55,  334,   55,  263,   55,  179,  264,
      275,   92,  333,  276,   47,   47,  332,   45,   49,   47,
       47,   81,  331,   50,  330,  329,   55,  328,  327,  326,
      325,  324,   92,  323,   92,  322,  321,  320,  319,  318,
      317,   47,   47,   47,  316,  315,  314,  313,  312,  311,

      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,   47,   83,   84,
      293,  292,  291,  290,  289,   85,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  274,  273,
      272,  271,  270,   86,  269,  268,   87,  267,  266,  265,
       88,  262,  261,  260,  259,  258,  257,  256,   89,  255,
      254,   90,  253,   91,   37,   37,   37,   41,   41,   41,
       43,   43,   43,   48,   48,   48,   82,   82,   82,   93,
       93,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,

      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  195,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  127,  126,  125,

      124,  123,   96,   96,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  100,   99,   98,   97,   53,   80,
       79,   69,   68,   67,   62,   53,  343,   42,   42,   11,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343

    } ;

static yyconst short int yy_chk[494] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    4,    4,    7,    7,    7,
        8,    8,    8,   17,   19,   17,   19,   20,   22,   13,
       25,   19,   36,  348,   24,   44,   25,   29,    3,   50,
        4,   20,   22,   20,   24,    7,  170,   29,    8,   31,
       19,   30,  170,   30,  340,   30,  172,   13,   30,  172,

       36,   31,  337,   44,   61,   61,    7,   50,    7,    8,
       30,    8,    9,  336,    9,    9,    9,    9,   13,  334,
       13,   36,   81,   36,   44,   52,   44,   52,   50,   53,
       50,   54,   52,   92,   53,  333,   54,  332,    9,    9,
        9,   55,   55,  154,  185,   55,  331,  185,  330,  185,
       81,   52,   94,   53,  329,   54,  245,   94,  154,  245,
      257,   92,  326,  257,    9,   10,  324,   10,   10,   10,
       10,   81,  323,   81,  321,  320,   94,  319,  317,  316,
      315,  314,   92,  313,   92,  312,  311,  310,  309,  308,
      307,   10,   10,   10,  306,  304,  303,  302,  301,  300,

      299,  298,  296,  295,  294,  293,  292,  291,  290,  288,
      285,  284,  283,  282,  281,  280,  277,   10,   40,   40,
      276,  275,  274,  272,  271,   40,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  256,  255,
      254,  253,  252,   40,  250,  249,   40,  248,  247,  246,
       40,  244,  243,  241,  240,  239,  238,  237,   40,  236,
      235,   40,  234,   40,  344,  344,  344,  345,  345,  345,
      346,  346,  346,  347,  347,  347,  349,  349,  349,  350,
      350,  233,  232,  231,  229,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  215,  214,  212,  211,

      210,  209,  208,  207,  206,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  187,  186,  184,  182,  181,  180,  179,  178,  177,
      175,  174,  173,  171,  169,  168,  166,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  153,  152,  151,
      150,  149,  147,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  137,  136,  135,  134,  133,  132,  131,  130,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  119,
      118,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,

       98,   97,   96,   95,   85,   80,   79,   78,   77,   76,
       75,   74,   73,   72,   71,   70,   69,   68,   67,   66,
       65,   64,   63,   62,   60,   59,   58,   57,   51,   33,
       32,   28,   27,   26,   23,   18,   11,    6,    5,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
#define INITIAL 0
/*
 * pbrt source code Copyright(c) 1998-2007 Matt Pharr and Greg Humphreys
 *
 * All Rights Reserved.
 * For educational use only; commercial use expressly forbidden.
 * NO WARRANTY, express or implied, for this software.
 * (See file License.txt for complete license)
 */
/* state used for include file stuff */
#line 13 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"

#define YY_MAIN 0
#define YY_NEVER_INTERACTIVE 1

#include "pbrt.h"
#include "api.h"

struct ParamArray;

#ifdef WIN32
#include "pbrtparse.hpp"
#else
#include "pbrtparse.h"
#endif

#ifdef WIN32
#pragma warning ( disable: 4244 )
#endif

struct IncludeInfo {
	string filename;
	YY_BUFFER_STATE bufState;
	int lineNum;
};
vector<IncludeInfo> includeStack;

extern int line_num;
int str_pos;

void add_string_char( char c )
{
	yylval.string[str_pos++] = c;
	yylval.string[str_pos] = '\0';
}

extern void yyerror( const char *str );
extern void ParseError( const char *format, ... ) PRINTF_FUNC;

void include_push(char *filename) {
	if (includeStack.size() > 32)
		Severe("Only 32 levels of nested Include allowed in scene files.");
	IncludeInfo ii;
	extern string current_file;
	ii.filename = current_file;
	ii.bufState = YY_CURRENT_BUFFER;
	ii.lineNum = line_num;
	includeStack.push_back(ii);

	current_file = filename;
	line_num = 1;

	yyin = fopen(filename, "r");
	if (!yyin)
		Severe("Unable to open included scene file \"%s\"", filename);
	yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
}

void include_pop(void)
{
	extern int line_num;
	extern string current_file;
	yy_delete_buffer(YY_CURRENT_BUFFER);
	yy_switch_to_buffer(includeStack.back().bufState);
	current_file = includeStack.back().filename;
	line_num = includeStack.back().lineNum;
	includeStack.pop_back();
}
#define YY_NO_UNPUT 1
#define STR 1
#define COMMENT 2
#define INCL 3
#define INCL_FILE 4

#line 674 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\/pbrtlex.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 86 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"

#line 838 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\/pbrtlex.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 344 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 440 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 87 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ BEGIN(INCL); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 88 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 89 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ BEGIN(INCL_FILE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 90 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ ParseError( "Illegal character following Include directive" ); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 92 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ ParseError( "Illegal character in Include file name" ); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 93 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{
	BEGIN(INITIAL);
	include_push(yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 97 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ BEGIN COMMENT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 98 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
/* eat it up */
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ line_num++; BEGIN INITIAL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return ACCELERATOR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return AREALIGHTSOURCE;	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return ATTRIBUTEBEGIN; 	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 103 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return ATTRIBUTEEND; 		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return CAMERA;		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return CONCATTRANSFORM; 	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 106 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return COORDINATESYSTEM;	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 107 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return COORDSYSTRANSFORM;	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 108 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return FILM;	 		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 109 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return IDENTITY;		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 110 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return LIGHTSOURCE;		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 111 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return LOOKAT;		}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 112 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return MATERIAL;		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 113 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return OBJECTBEGIN;		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 114 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return OBJECTEND;		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 115 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return OBJECTINSTANCE;	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 116 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return PIXELFILTER; 		}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 117 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return REVERSEORIENTATION;	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 118 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return ROTATE;		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 119 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return SAMPLER;		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 120 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return SEARCHPATH;		}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 121 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return SCALE;			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return SHAPE;			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 123 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return SURFACEINTEGRATOR;	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 124 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return TEXTURE;		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 125 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return TRANSFORMBEGIN;	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 126 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return TRANSFORMEND;	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 127 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return TRANSFORM;		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 128 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return TRANSLATE; 		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 129 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return VOLUME;		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 130 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return VOLUMEINTEGRATOR;	}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 131 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return WORLDBEGIN; 		}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 132 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return WORLDEND;		}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 133 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
/* do nothing */
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 134 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ line_num++; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 135 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{
  yylval.num = (float) atof(yytext);
  return NUM;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 139 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{
	strcpy( yylval.string, yytext );
	return ID;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 143 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return LBRACK; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 144 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ return RBRACK; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 145 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ BEGIN STR; str_pos = 0; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 146 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{add_string_char('\n');}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 147 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{add_string_char('\t');}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 148 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{add_string_char('\r');}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 149 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{add_string_char('\b');}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 150 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{add_string_char('\f');}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 151 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{add_string_char('\"');}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 152 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{add_string_char('\\');}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 153 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{
  int val = atoi(yytext+1);
  while(val > 256)
    val -= 256;
  add_string_char(val);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 159 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{line_num++;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 160 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ add_string_char(yytext[1]);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 161 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{BEGIN INITIAL; return STRING;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 162 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{add_string_char(yytext[0]);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 163 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ParseError("Unterminated string!");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 165 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
{ ParseError( "Illegal character: %c",yytext[0] ); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 166 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"
ECHO;
	YY_BREAK
#line 1260 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\/pbrtlex.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(INCL):
case YY_STATE_EOF(INCL_FILE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 53);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 344 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 53;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 344 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 343);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 166 "c:\\Users\\ktegan\\Downloads\\pbrt\\pbrt-1.03\\core\\pbrtlex.l"

int yywrap(void)
{
	if (includeStack.size() ==0) return 1;
	include_pop();
	BEGIN(INCL_FILE);
	return 0;
}

